site_name: Drupal VM CLI Documentation
theme: readthedocs
repo_url: https://github.com/opdavies/drupal-vm-generator

pages:
  - Home: 'index.md'
  - Installation:
      - 'Using the Installer': 'installation/installer.md'
      - 'Clone from GitHub': 'installation/github.md'
  - Commands:
      - 'config:generate': 'commands/config-generate.yml'
